/*
** hv_init.c -- runs at the end of sqlite3_initialize() in static builds
** (compiled with -DSQLITE_EXTRA_INIT=hv_extra_init): registers the httpvfs
** VFS and every statically linked extension, so each new connection gets the
** extensions automatically through sqlite3_auto_extension().
**
** hv_register_static_extensions() is generated by the Makefile from the list
** of extensions (build/<target>/ext_registry.c).
*/
#include "sqlite3.h"

int httpvfs_register(void);
void hv_register_static_extensions(void);

int hv_extra_init(const char *zNotUsed){
  int rc;
  (void)zNotUsed;
  rc = httpvfs_register();
  if( rc==SQLITE_OK ) hv_register_static_extensions();
  return rc;
}
