# wasm/build.mk -- native and WebAssembly builds of SQLite with the httpvfs VFS
# and the project's extensions. Included from the top-level Makefile; all
# paths are relative to the repository root. See wasm/NOTES.md.
#
# Extensions: every directory ext/<name>/ that contains .c files is one
# extension. All of its .c files are compiled together; its entry point must be
# sqlite3_<name>_init, where <name> is the directory name reduced to lower-case
# letters (ext/late -> sqlite3_late_init). Override the list with
#   make EXT_DIRS="ext/dense" ...
# In static builds (WASM, native CLI) the sources are compiled with
# -DSQLITE_CORE and each entry point is registered with sqlite3_auto_extension,
# so every connection gets every extension. Keep non-entry symbols static (or
# prefixed) so that extensions do not clash when linked together.

BUILD      ?= build
SQLITE_DIR := $(BUILD)/sqlite
NATIVE_DIR := $(BUILD)/native
WASM_DIR   := $(BUILD)/wasm
PKG_DIR    := wasm/pkg

EMSDK      ?= /home/user/emsdk
EMCC       ?= $(shell command -v emcc 2>/dev/null || echo $(EMSDK)/upstream/emscripten/emcc)
CC         ?= cc

EXT_DIRS   ?= $(patsubst %/,%,$(sort $(dir $(wildcard ext/*/*.c))))
EXT_NAMES  := $(notdir $(EXT_DIRS))
ext_entry   = sqlite3_$(shell printf '%s' '$(1)' | tr -cd 'A-Za-z' | tr 'A-Z' 'a-z')_init
EXT_SRCS   := $(foreach d,$(EXT_DIRS),$(wildcard $(d)/*.c))
EXT_HDRS   := $(foreach d,$(EXT_DIRS),$(wildcard $(d)/*.h))

HV_SRC     := wasm/src/httpvfs.c
HV_HDR     := wasm/src/httpvfs.h
DEMO_SRC   := wasm/demo_ext.c

# SQLite compile-time options shared by all builds.
SQLITE_OPTS := -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_DBSTAT_VTAB \
  -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_MATH_FUNCTIONS \
  -DSQLITE_DQS=0 -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS
EXT_INC     := -I$(SQLITE_DIR) -Iwasm/src

NATIVE_CFLAGS ?= -O2 -g
WASM_CFLAGS   ?= -O2 -msimd128
EXT_CFLAGS    ?=

.PHONY: sqlite native wasm wasm-asyncify wasm-jspi test test-native test-node test-browser clean-wasm

# ---------------------------------------------------------------- SQLite ---
sqlite: $(SQLITE_DIR)/sqlite3.c
$(SQLITE_DIR)/sqlite3.c $(SQLITE_DIR)/sqlite3.h $(SQLITE_DIR)/sqlite3ext.h $(SQLITE_DIR)/shell.c:
	wasm/scripts/fetch-sqlite.sh $(SQLITE_DIR)

# Generated: registers every statically linked extension.
define gen_registry
	@mkdir -p $(dir $@)
	@{ echo '/* generated by wasm/build.mk */'; \
	   echo '#include "sqlite3.h"'; \
	   for e in sqlite3_demoext_init $(foreach n,$(EXT_NAMES),$(call ext_entry,$(n))); do \
	     echo "int $$e(sqlite3*, char**, const void*);"; done; \
	   echo 'void hv_register_static_extensions(void){'; \
	   for e in sqlite3_demoext_init $(foreach n,$(EXT_NAMES),$(call ext_entry,$(n))); do \
	     echo "  sqlite3_auto_extension((void(*)(void))$$e);"; done; \
	   echo '}'; } > $@.tmp
	@cmp -s $@.tmp $@ || mv $@.tmp $@; rm -f $@.tmp
endef

$(NATIVE_DIR)/ext_registry.c $(WASM_DIR)/ext_registry.c: FORCE
	$(gen_registry)
FORCE:

# ---------------------------------------------------------------- native ---
# sqlite3 CLI (FTS5, httpvfs, all extensions built in),
# libsqlite3.so.0 (plain SQLite 3.53.4 for Python: LD_LIBRARY_PATH=build/native),
# loadable extensions: httpvfs.so, demo_ext.so, ext/<name>.so.
native: $(NATIVE_DIR)/sqlite3 $(NATIVE_DIR)/libsqlite3.so.0 $(NATIVE_DIR)/httpvfs.so \
        $(NATIVE_DIR)/demo_ext.so $(patsubst %,$(NATIVE_DIR)/ext/%.so,$(EXT_NAMES))

$(NATIVE_DIR)/sqlite3.o: $(SQLITE_DIR)/sqlite3.c
	@mkdir -p $(dir $@)
	$(CC) $(NATIVE_CFLAGS) $(SQLITE_OPTS) -DSQLITE_EXTRA_INIT=hv_extra_init -c $< -o $@

$(NATIVE_DIR)/sqlite3: $(NATIVE_DIR)/sqlite3.o $(SQLITE_DIR)/shell.c $(HV_SRC) $(HV_HDR) \
                       wasm/src/hv_init.c $(DEMO_SRC) $(EXT_SRCS) $(EXT_HDRS) $(NATIVE_DIR)/ext_registry.c
	$(CC) $(NATIVE_CFLAGS) $(SQLITE_OPTS) $(EXT_INC) -DSQLITE_CORE $(EXT_CFLAGS) \
	  $(SQLITE_DIR)/shell.c $(HV_SRC) wasm/src/hv_init.c $(DEMO_SRC) $(EXT_SRCS) \
	  $(NATIVE_DIR)/ext_registry.c $(NATIVE_DIR)/sqlite3.o -o $@ -lm -ldl -lpthread

$(NATIVE_DIR)/libsqlite3.so.0: $(SQLITE_DIR)/sqlite3.c
	@mkdir -p $(dir $@)
	$(CC) $(NATIVE_CFLAGS) $(SQLITE_OPTS) -fPIC -shared -Wl,-soname,libsqlite3.so.0 \
	  $< -o $@ -lm -ldl -lpthread
	ln -sf libsqlite3.so.0 $(NATIVE_DIR)/libsqlite3.so

$(NATIVE_DIR)/httpvfs.so: $(HV_SRC) $(HV_HDR) $(SQLITE_DIR)/sqlite3ext.h
	@mkdir -p $(dir $@)
	$(CC) $(NATIVE_CFLAGS) $(EXT_INC) -fPIC -shared $< -o $@

$(NATIVE_DIR)/demo_ext.so: $(DEMO_SRC) $(HV_HDR) $(SQLITE_DIR)/sqlite3ext.h
	@mkdir -p $(dir $@)
	$(CC) $(NATIVE_CFLAGS) $(EXT_INC) -fPIC -shared $< -o $@

.SECONDEXPANSION:
$(NATIVE_DIR)/ext/%.so: $$(wildcard ext/%/*.c) $$(wildcard ext/%/*.h) $(HV_HDR) $(SQLITE_DIR)/sqlite3ext.h
	@mkdir -p $(dir $@)
	$(CC) $(NATIVE_CFLAGS) $(EXT_INC) $(EXT_CFLAGS) -fPIC -shared $(filter %.c,$^) -o $@ -lm

# ------------------------------------------------------------------ wasm ---
# Two builds from the same objects:
#   asyncify (default; every browser and Node) -> $(PKG_DIR)/dist/sqlite-httpvfs.{mjs,wasm}
#   jspi     (Chromium >= 137; Node needs a flag) -> $(PKG_DIR)/dist/sqlite-httpvfs-jspi.{mjs,wasm}
WASM_SQLITE_OPTS := $(SQLITE_OPTS) -DSQLITE_THREADSAFE=0 -DSQLITE_OMIT_LOAD_EXTENSION \
  -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_SHARED_CACHE \
  -DSQLITE_TEMP_STORE=3 -DSQLITE_EXTRA_INIT=hv_extra_init
WASM_OBJS := $(WASM_DIR)/sqlite3.o $(WASM_DIR)/httpvfs.o $(WASM_DIR)/hv_init.o \
  $(WASM_DIR)/demo_ext.o $(WASM_DIR)/ext_registry.o $(patsubst %,$(WASM_DIR)/ext/%.o,$(EXT_NAMES))

WASM_EXPORTS := _malloc,_free,_sqlite3_open_v2,_sqlite3_close_v2,_sqlite3_exec,\
_sqlite3_prepare_v2,_sqlite3_step,_sqlite3_reset,_sqlite3_finalize,_sqlite3_clear_bindings,\
_sqlite3_bind_parameter_count,_sqlite3_bind_parameter_index,_sqlite3_bind_null,\
_sqlite3_bind_int64,_sqlite3_bind_double,_sqlite3_bind_text,_sqlite3_bind_blob,\
_sqlite3_column_count,_sqlite3_column_name,_sqlite3_column_type,_sqlite3_column_int64,\
_sqlite3_column_double,_sqlite3_column_text,_sqlite3_column_blob,_sqlite3_column_bytes,\
_sqlite3_errmsg,_sqlite3_errcode,_sqlite3_changes,_sqlite3_libversion,\
_sqlite3_db_release_memory,_sqlite3_file_control,\
_httpvfs_stats_array,_httpvfs_reset,_httpvfs_log_count,_httpvfs_log_copy,_httpvfs_now
# Exports that can block on the network (JSPI needs them listed).
WASM_ASYNC_EXPORTS := sqlite3_open_v2,sqlite3_exec,sqlite3_prepare_v2,sqlite3_step,sqlite3_file_control

WASM_LDFLAGS := -O2 -sMODULARIZE -sEXPORT_ES6 -sEXPORT_NAME=createSqliteHttpvfs \
  -sENVIRONMENT=web,worker,node -sALLOW_MEMORY_GROWTH -sINITIAL_MEMORY=32MB \
  -sSTACK_SIZE=1MB -sEXPORTED_FUNCTIONS=$(WASM_EXPORTS) \
  -sEXPORTED_RUNTIME_METHODS=ccall,UTF8ToString,stringToUTF8,lengthBytesUTF8,HEAPU8,HEAP32,HEAPU32,HEAPF64 \
  --pre-js wasm/src/httpvfs-pre.js

wasm: wasm-asyncify wasm-jspi
wasm-asyncify: $(PKG_DIR)/dist/sqlite-httpvfs.mjs
wasm-jspi: $(PKG_DIR)/dist/sqlite-httpvfs-jspi.mjs

$(WASM_DIR)/sqlite3.o: $(SQLITE_DIR)/sqlite3.c
	@mkdir -p $(dir $@)
	$(EMCC) $(WASM_CFLAGS) $(WASM_SQLITE_OPTS) -c $< -o $@
$(WASM_DIR)/httpvfs.o: $(HV_SRC) $(HV_HDR) $(SQLITE_DIR)/sqlite3ext.h
	@mkdir -p $(dir $@)
	$(EMCC) $(WASM_CFLAGS) $(EXT_INC) -DSQLITE_CORE -c $< -o $@
$(WASM_DIR)/hv_init.o: wasm/src/hv_init.c $(SQLITE_DIR)/sqlite3.h
	$(EMCC) $(WASM_CFLAGS) $(EXT_INC) -DSQLITE_CORE -c $< -o $@
$(WASM_DIR)/demo_ext.o: $(DEMO_SRC) $(HV_HDR) $(SQLITE_DIR)/sqlite3ext.h
	$(EMCC) $(WASM_CFLAGS) $(EXT_INC) -DSQLITE_CORE -c $< -o $@
$(WASM_DIR)/ext_registry.o: $(WASM_DIR)/ext_registry.c
	$(EMCC) $(WASM_CFLAGS) $(EXT_INC) -c $< -o $@
# One object per extension: its .c files concatenated into a single unit.
$(WASM_DIR)/ext/%.o: $$(wildcard ext/%/*.c) $$(wildcard ext/%/*.h) $(HV_HDR) $(SQLITE_DIR)/sqlite3ext.h
	@mkdir -p $(dir $@)
	$(EMCC) $(WASM_CFLAGS) $(EXT_INC) -DSQLITE_CORE $(EXT_CFLAGS) -r $(filter %.c,$^) -o $@

$(PKG_DIR)/dist/sqlite-httpvfs.mjs: $(WASM_OBJS) wasm/src/httpvfs-pre.js
	@mkdir -p $(dir $@)
	$(EMCC) $(WASM_OBJS) $(WASM_LDFLAGS) -sASYNCIFY -sASYNCIFY_STACK_SIZE=262144 -o $@

$(PKG_DIR)/dist/sqlite-httpvfs-jspi.mjs: $(WASM_OBJS) wasm/src/httpvfs-pre.js
	@mkdir -p $(dir $@)
	$(EMCC) $(WASM_OBJS) $(WASM_LDFLAGS) -sJSPI -sJSPI_EXPORTS=$(WASM_ASYNC_EXPORTS) -o $@

# ----------------------------------------------------------------- tests ---
test: test-native test-node test-browser
test-native: native
	python3 wasm/test/test_native.py
test-node: native wasm-asyncify
	node --test wasm/test/node.test.mjs
test-browser: native wasm
	node wasm/test/browser.test.mjs

clean-wasm:
	rm -rf $(NATIVE_DIR) $(WASM_DIR) $(PKG_DIR)/dist
